# -*- coding: utf-8 -*-
"""
Datos de los temas, preguntas y frases de IndustrialQuest.
"""

# Base de datos de temas de estudio gramaticales, audios, fondos y sus respectivas frases en inglés.
# Los textos visibles para el usuario permanecen en inglés para mantener el propósito educativo.
TEMAS = {
    "Simple Past": {
        "audio_fondo": "Stage1.wav",
        "audio_clic": "Correcta.wav",
        "audio_exito": "ganador.wav",
        "audio_fracaso": "equivocado.wav",
        "imagen_fondo": "PastSimple.png",  # Mapea a la clave original
        "imagen_corazon": "corazon.png",
        "frases": [
            ("She _ the tree (climb)", "climbed"),
            ("They _ for two hours (wait)", "waited"),
            ("The train _ at the station (stop)", "stopped"),
            ("We _ the suitcases from the airport (carry)", "carried"),
            ("Everybody _. It was a funny joke (laugh)", "laughed"),
            ("I did not _ home after work (walk)", "walk"),
            ("I did not _ the party last night (like)", "like"),
            ("We _ Seville University on the bus (pass)", "passed"),
            ("No one _ at the end of the song (clap)", "clapped"),
            ("Did mary _ yesterday? (walk)", "walk"),
            ("Did you _ your homework? (finish)", "finish"),
            ("Tom _ _ _ his grandmother (not/visit)", "did not visit"),
            ("Did you _ to your mother? (listen)", "listen"),
            ("Mary _ off the tree (fall)", "fell"),
            ("Did you _ your breakfast? (eat)", "eat"),
            ("Sarah _ her new car (wash)", "washed"),
            ("Did you _ the movie? (enjoy)", "enjoy"),
            ("Jack _ his phone (lose)", "lost"),
            ("Did you _ to the doctor? (go)", "go"),
            ("The children _ in the park (play)", "played"),
            ("You _ your keys (find)", "found"),
            ("Did you _ the news? (hear)", "hear"),
            ("Tim _ the train (miss)", "missed"),
            ("She _ her ankle (twist)", "twisted"),
            ("Did you _ the test? (take)", "take"),
            ("He _ the vase (break)", "broke"),
            ("Ben _ the game (watch)", "watched"),
            ("The children _ in the park (run)", "ran"),
            ("Shakira _ in the concert (sing)", "sang"),
            ("Pedro _ his shoes (wear)", "wore"),
            ("Did you _ your room? (clean)", "clean")
        ]
    },
    "Comparatives and Superlatives": {
        "audio_fondo": "Stage2.wav",
        "audio_clic": "Correcta.wav",
        "audio_exito": "ganador.wav",
        "audio_fracaso": "equivocado.wav",
        "imagen_fondo": "Comparativos.jpg",
        "imagen_corazon": "corazon.png",
        "frases": [
            ("La Paz is _ _ Santa Cruz (cold)", "colder than"),
            ("Bugatti is _ _ Ferrari (fast)", "faster than"),
            ("Susan is _ _ Maria (old)", "older than"),
            ("Health is _ _ than money (important)", "more important"),
            ("My sister is _ _ than Gina (lazy)", "lazier than"),
            ("He is _ _ in his class (young)", "the youngest"),
            ("Sarah is _ _ Emily (tall)", "taller than"),
            ("Coca cola is the _ _ drink ever (popular)", "most popular"),
            ("Patience is _ _ virtue (great)", "the greatest"),
            ("The sun is _ _ the Earth (hot)", "hotter than"),
            ("I am _ _ student in class (good)", "the best"),
            ("She is the _ _ in her family (intelligent)", "most intelligent"),
            ("My hair is _ _ yours (long)", "longer than"),
            ("Lago Titicaca is _ _ lake in Sudamerica (large)", "the largest"),
            ("Mike is _ _ Josh (fat)", "fatter than"),
            ("Oruro is _ _ city in Bolivia (coldest)", "the coldest"),
            ("Jim Carrey is _ _ Eugenio Derbez (funny)", "funnier than"),
            ("His score was _ _ in the competition (high)", "the highest"),
            ("A car is _ _ a motorcycle (heavy)", "heavier than"),
            ("My job is the _ _ stresful one (stresful)", "most stresful"),
            ("My house is _ _ yours (small)", "smaller than"),
            ("Chinese is the _ _ language (difficult)", "most difficult"),
            ("My dog is _ _ yours (friendly)", "friendlier than"),
            ("Mt. Everest is _ _ mountain in the world (tall)", "the tallest"),
            ("iPhone is _ _ than Samsung (expensive)", "more expensive"),
            ("Coffee is _ _ than tea (addictive)", "more addictive"),
            ("Steel is _ _ iron (hard)", "harder than"),
            ("This computer is _ _ I have used (fast)", "the fastest"),
            ("Jill is _ _ Gina (pretty)", "prettier than")
        ]
    },
    "Present Perfect": {
        "audio_fondo": "Stage3.wav",
        "audio_clic": "Correcta.wav",
        "audio_exito": "ganador.wav",
        "audio_fracaso": "equivocado.wav",
        "imagen_fondo": "PresentPerfect.png",
        "imagen_corazon": "corazon.png",
        "frases": [
            ("She _ _ to the movies (go)", "has gone"),
            ("I _ _ living in Bolivia this year(be)", "have been"),
            ("They _ _ bananas this morning (eat)", "have eaten"),
            ("Have you _ the letter? (write)", "written"),
            ("I _ _ dinner for us (cook)", "have cooked"),
            ("He _ _ that movie before (see)", "has seen"),
            ("We _ _ for the test (study)", "have studied"),
            ("It _ _ all day (rain)", "has rained"),
            ("Maria _ _ that book twice (read)", "has read"),
            ("Pedro _ _ the house (clean)", "has cleaned"),
            ("Oriente _ _ the championship (win)", "have won"),
            ("Miguel _ _ to the beach (go)", "has gone"),
            ("We _ _ the museum (visit)", "have visited"),
            ("Jeff _ _ the dog for a walk (take)", "has taken"),
            ("I _ _ the assignment (complete)", "have completed"),
            ("He _ _ to many countries (travel)", "has traveled"),
            ("I _ _ my degree (finish)", "have finished"),
            ("He _ _ his arm (break)", "has broken"),
            ("Has he _ to ski? (learn)", "learned"),
            ("Has she _ a new job? (find)", "found"),
            ("I _ _ your brother (meet)", "have met"),
            ("Has she _ a song? (sing)", "sung"),
            ("They _ _ the kitchen (renovate)", "have renovated"),
            ("Has he _ the driving test? (pass)", "passed"),
            ("Have they a_ a puppy? (adopt)", "adopted"),
            ("Has Luis _ spanish for two years? (study)", "studied"),
            ("I _ _ a mistake (make)", "have made"),
            ("Pedro _ _ Maria (kiss)", "has kissed")
        ]
    },
    "Future with will / going to": {
        "audio_fondo": "Stage4.wav",
        "audio_clic": "Correcta.wav",
        "audio_exito": "ganador.wav",
        "audio_fracaso": "equivocado.wav",
        "imagen_fondo": "Will.jpg",
        "imagen_corazon": "corazon.png",
        "frases": [
            ("I _ _ _ to Bolivia next year (won't/go)", "will not go"),
            ("I _ _ to the movies tonight (be/go)", "am going"),
            ("Pepe _ _ call you later (won't)", "will not"),
            ("She is _ _ _ a new business (go/start)", "going to start"),
            ("It _ _ tomorrow (will/rain)", "will rain"),
            ("Sasha _ _ a doctor (will/be)", "will be"),
            ("Pedro _ _ a car next month (will/buy)", "will buy"),
            ("She _ _ going to make dinner tonight (be/not)", "is not"),
            ("Will she _ to play the guitar? (learn)", "learn"),
            ("I _ _ you with your homework (will/help)", "will help"),
            ("She is _ _ _ a dance class (go/join)", "going to join"),
            ("I _ _ money for vacations (will/save)", "will save"),
            ("I _ _ _ my project next week (won't/finish)", "will not finish"),
            ("We are _ _ _ the project by tomorrow (go/complete)", "going to complete"),
            ("John _ _ _ the report by the deadline (won't/complete)", "will not complete"),
            ("She _ _ _ to me by tomorrow (won't/speak)", "will not speak"),
            (" _ she run the marathon next week? (will)", "will"),
            ("I am _ _ _ the walls right now (go/paint)", "going to paint"),
            ("I _ _ _ to call you on your birthday (won't/forget)", "will not forget"),
            ("I _ _ my birthday this year (will/celebrate)", "will celebrate"),
            ("Liam _ _ _ learn french this month (be/go)", "is going to"),
            ("I _ _ _ my birthday this year (won't/celebrate)", "will not celebrate"),
            ("She is _ _ _ to Europe tomorrow (go/travel)", "going to travel"),
            ("James is going to _ his kitchen next month (renovate)", "renovate"),
            ("Pedro _ _ with me for this (will/fight)", "will fight"),
            ("I am _ _ _ Game of Thrones (go/watch)", "going to watch"),
            ("This kid is _ _ _ very loud (go/scream)", "going to scream"),
            ("Carlos _ _ a lot of money (will/pay)", "will pay")
        ]
    }
}
