# -*- coding: utf-8 -*-
"""
Datos de los temas, preguntas y frases de IndustrialQuest: Woodwork Edition.
"""

TEMAS = {
    "Level 1: Reception Area": {
        "audio_fondo": "Stage1.wav",
        "audio_clic": "Correcta.wav",
        "audio_exito": "ganador.wav",
        "audio_fracaso": "equivocado.wav",
        "imagen_fondo": "Nivel_1_WareHouseZoneFinal.png",
        "imagen_corazon": "corazon.png",
        "regla": "Mixed Present and Past (Verb To Be: am, is, are, was, were)",
        "historia": "Production is about to start! A truck has just arrived with raw lumber, but the logs are incomplete. Complete the logs using the Verb To Be to validate the cargo before it enters.",
        "frases": [
            ("I ___ an industrial engineering student today.", "am"),
            ("He ___ a production supervisor yesterday.", "was"),
            ("The workers ___ in the factory now.", "are"),
            ("The machine ___ operational yesterday.", "was"),
            ("We ___ ready for the inspection today.", "are"),
            ("The warehouse ___ organized last week.", "was"),
            ("She ___ responsible for quality control now.", "is"),
            ("They ___ machine operators last year.", "were"),
            ("The report ___ complete today.", "is"),
            ("The materials ___ available yesterday.", "were"),
            ("I ___ in the laboratory now.", "am"),
            ("The supervisor ___ in the office this morning.", "was"),
            ("The employees ___ responsible workers today.", "are"),
            ("The product ___ ready for shipment yesterday.", "was"),
            ("We ___ part of the company last year.", "were"),
            ("The technicians ___ in the maintenance department now.", "are"),
            ("The forklift ___ in the warehouse yesterday.", "was"),
            ("She ___ very organized today.", "is"),
            ("The safety helmet ___ mandatory during the inspection.", ["was", "is"]),
            ("They ___ ready to start work now.", "are"),
            ("The production line ___ operational today.", "is"),
            ("The quality reports ___ complete last week.", "were"),
            ("The engineer ___ interested in industrial processes now.", "is"),
            ("The robot arm ___ functional during the test.", "was"),
            ("We ___ in a training session yesterday.", "were"),
            ("The operators ___ on the production line today.", "are"),
            ("The control panel ___ active during the night shift.", "was"),
            ("The warehouse ___ full today.", "is"),
            ("The products ___ ready for shipment now.", "are"),
            ("The supervisor ___ near the machine yesterday.", "was"),
            ("I ___ a future engineer today.", "am"),
            ("The employees ___ at the factory entrance this morning.", "were"),
            ("The machine ___ new today.", "is"),
            ("The backup batteries ___ fully charged yesterday.", "were"),
            ("We ___ prepared for the inspection now.", "are"),
            ("The quality inspector ___ responsible for inspections yesterday.", "was"),
            ("The materials ___ in the warehouse today.", "are"),
            ("The production schedule ___ updated last Friday.", "was"),
            ("The workers ___ very efficient now.", "are"),
            ("The air filters ___ clean during maintenance.", "were"),
            ("The technician ___ present during the audit.", "was"),
            ("She ___ in charge of quality assurance today.", "is"),
            ("The laboratory ___ clean and organized now.", "is"),
            ("The emergency lights ___ operational during the test.", "were"),
            ("The cutting machine ___ operational today.", "is"),
            ("The products ___ finished yesterday.", "were"),
            ("We ___ in the dispatch area now.", "are"),
            ("The manager ___ a good leader during the project.", "was"),
            ("The operators ___ ready today.", "are"),
            ("The main sensor ___ calibrated before production.", "was"),
            ("I ___ in the control room now.", "am"),
            ("The workers ___ in the assembly area yesterday.", "were"),
            ("The equipment ___ very useful today.", "is"),
            ("The technician ___ present yesterday.", "was"),
            ("We ___ industrial engineering students today.", "are"),
            ("The production manager ___ in a meeting this morning.", "was"),
            ("The robot arm ___ operational today.", "is"),
            ("The safety protocols ___ effective during the audit.", "were"),
            ("The employees ___ in the factory now.", "are"),
            ("The products ___ ready for export yesterday.", "were")
        ]
    },
    "Level 2: Production Area": {
        "audio_fondo": "Stage2.wav",
        "audio_clic": "Correcta.wav",
        "audio_exito": "ganador.wav",
        "audio_fracaso": "equivocado.wav",
        "imagen_fondo": "Nivel_2_ProductionLineFinal.png",
        "imagen_corazon": "corazon.png",
        "regla": "Present Continuous (Affirmative and Negative: e.g., 'am checking')",
        "historia": "The sawmill is active! The wood planks are moving on the conveyor belts, but the shift logs are incomplete. Use the Present Continuous (be + verb-ing) to describe current activities.",
        "frases": [
            ("I ______ (check) the production report.", "am checking"),
            ("He ______ (operate) the cutting machine.", "is operating"),
            ("She ______ (inspect) the finished products.", "is inspecting"),
            ("We ______ (assemble) furniture.", "are assembling"),
            ("You ______ (prepare) the shipment.", "are preparing"),
            ("They ______ (load) the truck.", "are loading"),
            ("The machine ______ (cut) wood.", "is cutting"),
            ("The supervisor ______ (review) the schedule.", "is reviewing"),
            ("The workers ______ (assemble) chairs.", "are assembling"),
            ("The engineer ______ (analyze) the process.", "is analyzing"),
            ("We ______ (attend) a safety meeting.", "are attending"),
            ("The operators ______ (control) the equipment.", "are controlling"),
            ("The forklift ______ (transport) materials.", "is transporting"),
            ("They ______ (package) the products.", "are packaging"),
            ("The technician ______ (repair) the machine.", "is repairing"),
            ("He ______ (inspect) the control panel.", "is inspecting"),
            ("She ______ (record) production data.", "is recording"),
            ("The robot ______ (move) the boxes.", "is moving"),
            ("We ______ (improve) the production process.", "are improving"),
            ("The employees ______ (clean) the work area.", "are cleaning"),
            ("The production manager ______ (conduct) a meeting.", "is conducting"),
            ("We ______ (check) the safety equipment.", "are checking"),
            ("The warehouse team ______ (receive) materials.", ["is receiving", "are receiving"]),
            ("The supervisor ______ (evaluate) worker performance.", "is evaluating"),
            ("She ______ (prepare) the quality report.", "is preparing"),
            ("The machine ______ (operate) normally.", "is operating"),
            ("You ______ (measure) the materials.", "are measuring"),
            ("The technicians ______ (install) new sensors.", "are installing"),
            ("The forklift ______ (unload) materials.", "is unloading"),
            ("They ______ (prepare) customer orders.", "are preparing"),
            ("The quality team ______ (inspect) the products.", ["is inspecting", "are inspecting"]),
            ("He ______ (calibrate) the equipment.", "is calibrating"),
            ("She ______ (supervise) the assembly process.", "is supervising"),
            ("The operators ______ (monitor) the control system.", "are monitoring"),
            ("We ______ (complete) the production schedule.", "are completing"),
            ("You ______ (check) the inventory.", "are checking"),
            ("The workers ______ (paint) the furniture.", "are painting"),
            ("The engineer ______ (design) a new process.", "is designing"),
            ("We ______ (verify) the measurements.", "are verifying"),
            ("They ______ (transport) finished products.", "are transporting"),
            ("The maintenance team ______ (repair) the conveyor belt.", ["is repairing", "are repairing"]),
            ("The production line ______ (operate) efficiently.", "is operating"),
            ("The employees ______ (sort) the materials.", "are sorting"),
            ("The inspector ______ (verify) quality standards.", "is verifying"),
            ("We ______ (prepare) the dispatch documents.", "are preparing"),
            ("You ______ (review) the technical report.", "are reviewing"),
            ("The machine ______ (produce) wooden panels.", "is producing"),
            ("The operators ______ (adjust) the equipment.", "are adjusting"),
            ("The technicians ______ (test) the sensors.", "are testing"),
            ("The manager ______ (plan) tomorrow's production activities.", "is planning"),
            ("I ______ (organize) the inventory.", "am organizing"),
            ("He ______ (monitor) the production line.", "is monitoring"),
            ("She ______ (update) the database.", "is updating"),
            ("We ______ (discuss) the project.", "are discussing"),
            ("The workers ______ (move) the materials.", "are moving"),
            ("The engineer ______ (calculate) production costs.", "is calculating"),
            ("The supervisor ______ (inspect) the warehouse.", "is inspecting"),
            ("The operators ______ (start) the machines.", "are starting"),
            ("The technician ______ (install) a control panel.", "is installing"),
            ("They ______ (finish) the production order.", "are finishing")
        ]
    },
    "Level 3: Assembly Area": {
        "audio_fondo": "Stage3.wav",
        "audio_clic": "Correcta.wav",
        "audio_exito": "ganador.wav",
        "audio_fracaso": "equivocado.wav",
        "imagen_fondo": "Nivel_3_QualityControlLaboratoryFinal.png",
        "imagen_corazon": "corazon.png",
        "regla": "Present Simple (correctly conjugated: base form or -s/-es)",
        "historia": "The wooden parts have arrived in the Assembly Area. Correct the assembly logs using the Present Simple of the action verbs based on subject agreement.",
        "frases": [
            ("The workers ______ (assemble) furniture pieces.", "assemble"),
            ("The technician ______ (check) the quality of each product.", "checks"),
            ("The engineer ______ (design) assembly plans.", "designs"),
            ("The team ______ (work) on the production line.", ["works", "work"]),
            ("The supervisor ______ (monitor) the process.", "monitors"),
            ("They ______ (build) wooden chairs.", "build"),
            ("He ______ (inspect) every finished product.", "inspects"),
            ("She ______ (organize) the work schedule.", "organizes"),
            ("The operators ______ (tighten) screws on the furniture.", "tighten"),
            ("The machine ______ (cut) precise parts.", "cuts"),
            ("The workers ______ (fix) defective pieces.", "fix"),
            ("The engineer ______ (calculate) production time.", "calculates"),
            ("The team ______ (follow) safety rules.", ["follows", "follow"]),
            ("The supervisor ______ (check) each station.", "checks"),
            ("The employees ______ (report) production errors.", "report"),
            ("He ______ (assemble) cabinet doors.", "assembles"),
            ("She ______ (paint) wooden surfaces.", "paints"),
            ("The workers ______ (move) materials carefully.", "move"),
            ("The machine ______ (produce) identical parts.", "produces"),
            ("The technician ______ (adjust) the equipment.", "adjusts"),
            ("The team ______ (complete) the assembly process.", ["completes", "complete"]),
            ("The engineer ______ (verify) measurements.", "verifies"),
            ("The supervisor ______ (assign) tasks daily.", "assigns"),
            ("The workers ______ (clean) the workstation.", "clean"),
            ("She ______ (check) production details.", "checks"),
            ("They ______ (assemble) tables and chairs.", "assemble"),
            ("The operator ______ (use) power tools.", "uses"),
            ("The technician ______ (replace) damaged parts.", "replaces"),
            ("The team ______ (follow) instructions carefully.", ["follows", "follow"]),
            ("The supervisor ______ (evaluate) performance.", "evaluates"),
            ("The workers ______ (pack) finished furniture.", "pack"),
            ("He ______ (review) technical drawings.", "reviews"),
            ("She ______ (label) completed products.", "labels"),
            ("The machine ______ (drill) holes in wood.", "drills"),
            ("The team ______ (measure) materials.", ["measures", "measure"]),
            ("The engineer ______ (inspect) final assembly.", "inspects"),
            ("The workers ______ (assemble) products quickly.", "assemble"),
            ("The supervisor ______ (control) quality standards.", "controls"),
            ("They ______ (organize) production flow.", "organize"),
            ("The technician ______ (test) assembled items.", "tests"),
            ("The workers ______ (follow) instructions from the supervisor.", "follow"),
            ("He ______ (operate) tools safely.", "operates"),
            ("She ______ (check) every detail.", "checks"),
            ("The team ______ (work) efficiently.", ["works", "work"]),
            ("The machine ______ (support) the assembly process.", "supports"),
            ("The workers ______ (complete) daily targets.", "complete"),
            ("The engineer ______ (improve) production methods.", "improves"),
            ("The supervisor ______ (reduce) errors in assembly.", "reduces"),
            ("They ______ (handle) materials carefully.", "handle"),
            ("The technician ______ (support) the production line.", "supports"),
            ("The workers ______ (assemble) products on time.", "assemble"),
            ("He ______ (manage) the team.", "manages"),
            ("She ______ (control) quality inspection.", "controls"),
            ("The team ______ (increase) productivity.", ["increases", "increase"]),
            ("The supervisor ______ (coordinate) activities.", "coordinates"),
            ("The engineer ______ (analyze) results.", "analyzes"),
            ("The workers ______ (maintain) order in the area.", "maintain"),
            ("The technician ______ (repair) tools when needed.", "repairs"),
            ("The team ______ (follow) production standards.", ["follows", "follow"]),
            ("The supervisor ______ (guide) the workers.", "guides")
        ]
    },
    "Level 4: Quality Control & Dispatch": {
        "audio_fondo": "Stage4.wav",
        "audio_clic": "Correcta.wav",
        "audio_exito": "ganador.wav",
        "audio_fracaso": "equivocado.wav",
        "imagen_fondo": "Nivel_4_LogisticsAndShippingCenterFinal.png",
        "imagen_corazon": "corazon.png",
        "regla": "Mixed grammar: To Be, Present Simple, Present Continuous, and Questions.",
        "historia": "Final audit! Check the final dispatch sheets. Apply all verb forms you have mastered (To Be, Present Simple, Present Continuous, Questions) before loading the cargo truck.",
        "frases": [
            ("The machine ___ operational today.", "is"),
            ("The workers ___ ready for shipment.", "are"),
            ("I ___ an industrial engineering student.", "am"),
            ("The warehouse ___ organized yesterday.", "was"),
            ("The supervisor ___ responsible for quality control.", "is"),
            ("The engineer ___ (check) the production report.", ["checks", "is checking"]),
            ("The workers ___ (assemble) furniture for dispatch.", ["assemble", "are assembling"]),
            ("The technician ___ (inspect) the final products.", ["inspects", "is inspecting"]),
            ("The team ___ (pack) the finished furniture.", ["packs", "is packing", "pack"]),
            ("The manager ___ (review) quality standards.", ["reviews", "is reviewing"]),
            ("___ the machine operational today?", "Is"),
            ("___ the workers ready for shipment?", "Are"),
            ("___ the supervisor responsible for inspection?", "Is"),
            ("___ the warehouse organized yesterday?", "Was"),
            ("___ the products ready for delivery?", "Are"),
            ("The production line ___ active now.", "is"),
            ("The workers ___ in the dispatch area yesterday.", "were"),
            ("The engineer ___ interested in quality control.", "is"),
            ("The machine ___ (operate) correctly at the moment.", "is operating"),
            ("The team ___ (check) final measurements.", ["checks", "is checking", "check"]),
            ("The supervisor ___ (evaluate) worker performance.", ["evaluates", "is evaluating"]),
            ("The workers ___ (load) the truck now.", "are loading"),
            ("The technician ___ (repair) equipment during inspection.", ["repairs", "is repairing", "repaired"]),
            ("The quality team ___ (verify) product standards.", ["verifies", "is verifying", "verify"]),
            ("The manager ___ (conduct) a final meeting.", ["conducts", "is conducting"]),
            ("The products ___ finished yesterday.", "were"),
            ("The warehouse ___ full today.", "is"),
            ("The materials ___ available during production.", ["were", "are"]),
            ("The robot arm ___ functional during the test.", "was"),
            ("The control panel ___ active yesterday.", "was"),
            ("The workers ___ very efficient today.", "are"),
            ("The engineer ___ responsible for the project.", ["is", "was"]),
            ("The supervisor ___ in the office now.", "is"),
            ("The technician ___ (calibrate) the machines.", ["calibrates", "is calibrating"]),
            ("The team ___ (organize) dispatch documents.", ["organizes", "is organizing", "organize"]),
            ("___ the machine new?", "Is"),
            ("___ the workers in the factory now?", "Are"),
            ("___ the supervisor present yesterday?", "Was"),
            ("___ the products ready for shipment?", "Are"),
            ("___ the report complete last week?", "Was"),
            ("The workers ___ (assemble) final products.", ["assemble", "are assembling"]),
            ("The engineer ___ (design) improvements now.", "is designing"),
            ("The technician ___ (test) equipment at the moment.", "is testing"),
            ("The supervisor ___ (monitor) production today.", ["is monitoring", "monitors"]),
            ("The team ___ (prepare) delivery orders.", ["prepares", "is preparing", "prepare"]),
            ("The machine ___ operational during the audit.", "was"),
            ("The workers ___ in the assembly area now.", "are"),
            ("The products ___ ready for export yesterday.", "were"),
            ("The engineer ___ a good leader.", ["is", "was"]),
            ("The warehouse ___ organized and clean.", ["is", "was"]),
            ("The technician ___ present during inspection.", "was"),
            ("The team ___ responsible for quality control.", ["is", "are"]),
            ("The supervisor ___ checking final reports.", ["is", "was"]),
            ("The workers ___ loading the truck now.", "are"),
            ("The machine ___ cutting wood yesterday.", "was"),
            ("___ the engineer in the office today?", "Is"),
            ("___ the workers ready now?", "Are"),
            ("___ the warehouse full yesterday?", "Was"),
            ("___ the products finished today?", "Are"),
            ("___ the supervisor responsible for quality control?", "Is")
        ]
    }
}
