# -*- coding: utf-8 -*-
"""
Diccionario de traducciones para las frases en IndustrialQuest: Woodwork Edition.
"""

TRADUCCIONES = {
    # === LEVEL 1 ===
    "I ___ an industrial engineering student today.": "Hoy soy un estudiante de ingeniería industrial.",
    "He ___ a production supervisor yesterday.": "Él era un supervisor de producción ayer.",
    "The workers ___ in the factory now.": "Los trabajadores están en la fábrica ahora.",
    "The machine ___ operational yesterday.": "La máquina estaba operativa ayer.",
    "We ___ ready for the inspection today.": "Nosotros estamos listos para la inspección hoy.",
    "The warehouse ___ organized last week.": "El almacén estaba organizado la semana pasada.",
    "She ___ responsible for quality control now.": "Ella es responsable del control de calidad ahora.",
    "They ___ machine operators last year.": "Ellos eran operadores de máquinas el año pasado.",
    "The report ___ complete today.": "El reporte está completo hoy.",
    "The materials ___ available yesterday.": "Los materiales estaban disponibles ayer.",
    "I ___ in the laboratory now.": "Yo estoy en el laboratorio ahora.",
    "The supervisor ___ in the office this morning.": "El supervisor estaba en la oficina esta mañana.",
    "The employees ___ responsible workers today.": "Los empleados son trabajadores responsables hoy.",
    "The product ___ ready for shipment yesterday.": "El producto estaba listo para el envío ayer.",
    "We ___ part of the company last year.": "Nosotros éramos parte de la empresa el año pasado.",
    "The technicians ___ in the maintenance department now.": "Los técnicos están en el departamento de mantenimiento ahora.",
    "The forklift ___ in the warehouse yesterday.": "La carretilla elevadora estaba en el almacén ayer.",
    "She ___ very organized today.": "Ella es muy organizada hoy.",
    "The safety helmet ___ mandatory during the inspection.": "El casco de seguridad era/es obligatorio durante la inspección.",
    "They ___ ready to start work now.": "Ellos están listos para comenzar a trabajar ahora.",
    "The production line ___ operational today.": "La línea de producción está operativa hoy.",
    "The quality reports ___ complete last week.": "Los reportes de calidad estaban completos la semana pasada.",
    "The engineer ___ interested in industrial processes now.": "El ingeniero está interesado en los procesos industriales ahora.",
    "The robot arm ___ functional during the test.": "El brazo robótico era funcional durante la prueba.",
    "We ___ in a training session yesterday.": "Nosotros estábamos en una sesión de capacitación ayer.",
    "The operators ___ on the production line today.": "Los operadores están en la línea de producción hoy.",
    "The control panel ___ active during the night shift.": "El panel de control estaba activo durante el turno de noche.",
    "The warehouse ___ full today.": "El almacén está lleno hoy.",
    "The products ___ ready for shipment now.": "Los productos están listos para el envío ahora.",
    "The supervisor ___ near the machine yesterday.": "El supervisor estaba cerca de la máquina ayer.",
    "I ___ a future engineer today.": "Yo soy un futuro ingeniero hoy.",
    "The employees ___ at the factory entrance this morning.": "Los empleados estaban en la entrada de la fábrica esta mañana.",
    "The machine ___ new today.": "La máquina es nueva hoy.",
    "The backup batteries ___ fully charged yesterday.": "Las baterías de respaldo estaban completamente cargadas ayer.",
    "We ___ prepared for the inspection now.": "Nosotros estamos preparados para la inspección ahora.",
    "The quality inspector ___ responsible for inspections yesterday.": "El inspector de calidad era responsable de las inspecciones ayer.",
    "The materials ___ in the warehouse today.": "Los materiales están en el almacén hoy.",
    "The production schedule ___ updated last Friday.": "El cronograma de producción fue actualizado el viernes pasado.",
    "The workers ___ very efficient now.": "Los trabajadores son muy eficientes ahora.",
    "The air filters ___ clean during maintenance.": "Los filtros de aire estaban limpios durante el mantenimiento.",
    "The technician ___ present during the audit.": "El técnico estaba presente durante la auditoría.",
    "She ___ in charge of quality assurance today.": "Ella está a cargo del aseguramiento de la calidad hoy.",
    "The laboratory ___ clean and organized now.": "El laboratorio está limpio y organizado ahora.",
    "The emergency lights ___ operational during the test.": "Las luces de emergencia estaban operativas durante la prueba.",
    "The cutting machine ___ operational today.": "La máquina de corte está operativa hoy.",
    "The products ___ finished yesterday.": "Los productos fueron terminados ayer.",
    "We ___ in the dispatch area now.": "Nosotros estamos en el área de despacho ahora.",
    "The manager ___ a good leader during the project.": "El gerente fue un buen líder durante el proyecto.",
    "The operators ___ ready today.": "Los operadores están listos hoy.",
    "The main sensor ___ calibrated before production.": "El sensor principal fue calibrado antes de la producción.",
    "I ___ in the control room now.": "Yo estoy en la sala de control ahora.",
    "The workers ___ in the assembly area yesterday.": "Los trabajadores estaban en el área de ensamblaje ayer.",
    "The equipment ___ very useful today.": "El equipo es muy útil hoy.",
    "The technician ___ present yesterday.": "El técnico estaba presente ayer.",
    "We ___ industrial engineering students today.": "Nosotros somos estudiantes de ingeniería industrial hoy.",
    "The production manager ___ in a meeting this morning.": "El gerente de producción estaba en una reunión esta mañana.",
    "The robot arm ___ operational today.": "El brazo robótico está operativo hoy.",
    "The safety protocols ___ effective during the audit.": "Los protocolos de seguridad fueron efectivos durante la auditoría.",
    "The employees ___ in the factory now.": "Los empleados están en la fábrica ahora.",
    "The products ___ ready for export yesterday.": "Los productos estaban listos para la exportación ayer.",

    # === LEVEL 2 ===
    "I ______ (check) the production report.": "Estoy revisando el reporte de producción.",
    "He ______ (operate) the cutting machine.": "Él está operando la máquina de corte.",
    "She ______ (inspect) the finished products.": "Ella está inspeccionando los productos terminados.",
    "We ______ (assemble) furniture.": "Estamos ensamblando muebles.",
    "You ______ (prepare) the shipment.": "Estás preparando el envío.",
    "They ______ (load) the truck.": "Ellos están cargando el camión.",
    "The machine ______ (cut) wood.": "La máquina está cortando madera.",
    "The supervisor ______ (review) the schedule.": "El supervisor está revisando el cronograma.",
    "The workers ______ (assemble) chairs.": "Los trabajadores están ensamblando sillas.",
    "The engineer ______ (analyze) the process.": "El ingeniero está analizando el proceso.",
    "We ______ (attend) a safety meeting.": "Estamos asistiendo a una reunión de seguridad.",
    "The operators ______ (control) the equipment.": "Los operadores están controlando el equipo.",
    "The forklift ______ (transport) materials.": "La carretilla elevadora está transportando materiales.",
    "They ______ (package) the products.": "Ellos están empaquetando los productos.",
    "The technician ______ (repair) the machine.": "El técnico está reparando la máquina.",
    "He ______ (inspect) the control panel.": "Él está inspeccionando el panel de control.",
    "She ______ (record) production data.": "Ella está registrando los datos de producción.",
    "The robot ______ (move) the boxes.": "El robot está moviendo las cajas.",
    "We ______ (improve) the production process.": "Estamos mejorando el proceso de producción.",
    "The employees ______ (clean) the work area.": "Los empleados están limpiando el área de trabajo.",
    "The production manager ______ (conduct) a meeting.": "El gerente de producción está dirigiendo una reunión.",
    "We ______ (check) the safety equipment.": "Estamos revisando el equipo de seguridad.",
    "The warehouse team ______ (receive) materials.": "El equipo del almacén está recibiendo materiales.",
    "The supervisor ______ (evaluate) worker performance.": "El supervisor está evaluando el rendimiento del trabajador.",
    "She ______ (prepare) the quality report.": "Ella está preparando el reporte de calidad.",
    "The machine ______ (operate) normally.": "La máquina está operando normalmente.",
    "You ______ (measure) the materials.": "Estás midiendo los materiales.",
    "The technicians ______ (install) new sensors.": "Los técnicos están instalando nuevos sensores.",
    "The forklift ______ (unload) materials.": "La carretilla elevadora está descargando materiales.",
    "They ______ (prepare) customer orders.": "Ellos están preparando los pedidos de los clientes.",
    "The quality team ______ (inspect) the products.": "El equipo de calidad está inspeccionando los productos.",
    "He ______ (calibrate) the equipment.": "Él está calibrando el equipo.",
    "She ______ (supervise) the assembly process.": "Ella está supervisando el proceso de ensamblaje.",
    "The operators ______ (monitor) the control system.": "Los operadores están monitoreando el sistema de control.",
    "We ______ (complete) the production schedule.": "Estamos completando el cronograma de producción.",
    "You ______ (check) the inventory.": "Estás revisando el inventario.",
    "The workers ______ (paint) the furniture.": "Los trabajadores están pintando los muebles.",
    "The engineer ______ (design) a new process.": "El ingeniero está diseñando un nuevo proceso.",
    "We ______ (verify) the measurements.": "Estamos verificando las medidas.",
    "They ______ (transport) finished products.": "Ellos están transportando productos terminados.",
    "The maintenance team ______ (repair) the conveyor belt.": "El equipo de mantenimiento está reparando la cinta transportadora.",
    "The production line ______ (operate) efficiently.": "La línea de producción está operando eficientemente.",
    "The employees ______ (sort) the materials.": "Los empleados están clasificando los materiales.",
    "The inspector ______ (verify) quality standards.": "El inspector está verificando los estándares de calidad.",
    "We ______ (prepare) the dispatch documents.": "Estamos preparando los documentos de despacho.",
    "You ______ (review) the technical report.": "Estás revisando el reporte técnico.",
    "The machine ______ (produce) wooden panels.": "La máquina está produciendo paneles de madera.",
    "The operators ______ (adjust) the equipment.": "Los operadores están ajustando el equipo.",
    "The technicians ______ (test) the sensors.": "Los técnicos están probando los sensores.",
    "The manager ______ (plan) tomorrow's production activities.": "El gerente está planificando las actividades de producción de mañana.",
    "I ______ (organize) the inventory.": "Estoy organizando el inventario.",
    "He ______ (monitor) the production line.": "Él está monitoreando la línea de producción.",
    "She ______ (update) the database.": "Ella está actualizando la base de datos.",
    "We ______ (discuss) the project.": "Estamos discutiendo el proyecto.",
    "The workers ______ (move) the materials.": "Los trabajadores están moviendo los materiales.",
    "The engineer ______ (calculate) production costs.": "El ingeniero está calculando los costos de producción.",
    "The supervisor ______ (inspect) the warehouse.": "El supervisor está inspeccionando el almacén.",
    "The operators ______ (start) the machines.": "Los operadores están encendiendo las máquinas.",
    "The technician ______ (install) a control panel.": "El técnico está instalando un panel de control.",
    "They ______ (finish) the production order.": "Ellos están terminando la orden de producción.",

    # === LEVEL 3 ===
    "The workers ______ (assemble) furniture pieces.": "Los trabajadores ensamblan piezas de muebles.",
    "The technician ______ (check) the quality of each product.": "El técnico revisa la calidad de cada producto.",
    "The engineer ______ (design) assembly plans.": "El ingeniero diseña planos de ensamblaje.",
    "The team ______ (work) on the production line.": "El equipo trabaja en la línea de producción.",
    "The supervisor ______ (monitor) the process.": "El supervisor monitorea el proceso.",
    "They ______ (build) wooden chairs.": "Ellos construyen sillas de madera.",
    "He ______ (inspect) every finished product.": "Él inspecciona cada producto terminado.",
    "She ______ (organize) the work schedule.": "Ella organiza el horario de trabajo.",
    "The operators ______ (tighten) screws on the furniture.": "Los operadores aprietan los tornillos en los muebles.",
    "The machine ______ (cut) precise parts.": "La máquina corta piezas precisas.",
    "The workers ______ (fix) defective pieces.": "Los trabajadores reparan piezas defectuosas.",
    "The engineer ______ (calculate) production time.": "El ingeniero calcula el tiempo de producción.",
    "The team ______ (follow) safety rules.": "El equipo sigue las reglas de seguridad.",
    "The supervisor ______ (check) each station.": "El supervisor revisa cada estación.",
    "The employees ______ (report) production errors.": "Los empleados informan de errores de producción.",
    "He ______ (assemble) cabinet doors.": "Él ensambla puertas de armarios.",
    "She ______ (paint) wooden surfaces.": "Ella pinta superficies de madera.",
    "The workers ______ (move) materials carefully.": "Los trabajadores mueven los materiales con cuidado.",
    "The machine ______ (produce) identical parts.": "La máquina produce piezas idénticas.",
    "The technician ______ (adjust) the equipment.": "El técnico ajusta el equipo.",
    "The team ______ (complete) the assembly process.": "El equipo completa el proceso de ensamblaje.",
    "The engineer ______ (verify) measurements.": "El ingeniero verifica las medidas.",
    "The supervisor ______ (assign) tasks daily.": "El supervisor asigna tareas diariamente.",
    "The workers ______ (clean) the workstation.": "Los trabajadores limpian la estación de trabajo.",
    "She ______ (check) production details.": "Ella revisa los detalles de producción.",
    "They ______ (assemble) tables and chairs.": "Ellos ensamblan mesas y sillas.",
    "The operator ______ (use) power tools.": "El operador usa herramientas eléctricas.",
    "The technician ______ (replace) damaged parts.": "El técnico reemplaza las piezas dañadas.",
    "The team ______ (follow) instructions carefully.": "El equipo sigue las instrucciones cuidadosamente.",
    "The supervisor ______ (evaluate) performance.": "El supervisor evalúa el rendimiento.",
    "The workers ______ (pack) finished furniture.": "Los trabajadores empaquetan los muebles terminados.",
    "He ______ (review) technical drawings.": "Él revisa los planos técnicos.",
    "She ______ (label) completed products.": "Ella etiqueta los productos terminados.",
    "The machine ______ (drill) holes in wood.": "La máquina perfora agujeros en la madera.",
    "The team ______ (measure) materials.": "El equipo mide los materiales.",
    "The engineer ______ (inspect) final assembly.": "El ingeniero inspecciona el ensamblaje final.",
    "The workers ______ (assemble) products quickly.": "Los trabajadores ensamblan productos rápidamente.",
    "The supervisor ______ (control) quality standards.": "El supervisor controla los estándares de calidad.",
    "They ______ (organize) production flow.": "Ellos organizan el flujo de producción.",
    "The technician ______ (test) assembled items.": "El técnico prueba los artículos ensamblados.",
    "The workers ______ (follow) instructions from the supervisor.": "Los trabajadores siguen las instrucciones del supervisor.",
    "He ______ (operate) tools safely.": "Él opera las herramientas de forma segura.",
    "She ______ (check) every detail.": "Ella revisa cada detalle.",
    "The team ______ (work) efficiently.": "El equipo trabaja eficientemente.",
    "The machine ______ (support) the assembly process.": "La máquina apoya el proceso de ensamblaje.",
    "The workers ______ (complete) daily targets.": "Los trabajadores completan los objetivos diarios.",
    "The engineer ______ (improve) production methods.": "El ingeniero mejora los métodos de producción.",
    "The supervisor ______ (reduce) errors in assembly.": "El supervisor reduce los errores en el ensamblaje.",
    "They ______ (handle) materials carefully.": "Ellos manipulan los materiales con cuidado.",
    "The technician ______ (support) the production line.": "El técnico apoya la línea de producción.",
    "The workers ______ (assemble) products on time.": "Los trabajadores ensamblan los productos a tiempo.",
    "He ______ (manage) the team.": "Él dirige al equipo.",
    "She ______ (control) quality inspection.": "Ella controla la inspección de calidad.",
    "The team ______ (increase) productivity.": "El equipo aumenta la productividad.",
    "The supervisor ______ (coordinate) activities.": "El supervisor coordina las actividades.",
    "The engineer ______ (analyze) results.": "El ingeniero analiza los resultados.",
    "The workers ______ (maintain) order in the area.": "Los trabajadores mantienen el orden en el área.",
    "The technician ______ (repair) tools when needed.": "El técnico repara las herramientas cuando es necesario.",
    "The team ______ (follow) production standards.": "El equipo sigue los estándares de producción.",
    "The supervisor ______ (guide) the workers.": "El supervisor guía a los trabajadores.",

    # === LEVEL 4 ===
    "The machine ___ operational today.": "La máquina está/estaba operativa hoy.",
    "The workers ___ ready for shipment.": "Los trabajadores están listos para el envío.",
    "I ___ an industrial engineering student.": "Yo soy un estudiante de ingeniería industrial.",
    "The warehouse ___ organized yesterday.": "El almacén estaba organizado ayer.",
    "The supervisor ___ responsible for quality control.": "El supervisor es responsable del control de calidad.",
    "The engineer ___ (check) the production report.": "El ingeniero revisa el reporte de producción.",
    "The workers ___ (assemble) furniture for dispatch.": "Los trabajadores ensamblan muebles para el despacho.",
    "The technician ___ (inspect) the final products.": "El técnico inspecciona los productos finales.",
    "The team ___ (pack) the finished furniture.": "El equipo empaqueta los muebles terminados.",
    "The manager ___ (review) quality standards.": "El gerente revisa los estándares de calidad.",
    "___ the machine operational today?": "¿Está la máquina operativa hoy?",
    "___ the workers ready for shipment?": "¿Están los trabajadores listos para el envío?",
    "___ the supervisor responsible for inspection?": "¿Es el supervisor responsable de la inspección?",
    "___ the warehouse organized yesterday?": "¿Estaba el almacén organizado ayer?",
    "___ the products ready for delivery?": "¿Están los productos listos para la entrega?",
    "The production line ___ active now.": "La línea de producción está activa ahora.",
    "The workers ___ in the dispatch area yesterday.": "Los trabajadores estaban en el área de despacho ayer.",
    "The engineer ___ interested in quality control.": "El ingeniero está interesado en el control de calidad.",
    "The machine ___ (operate) correctly at the moment.": "La máquina está operando correctamente en este momento.",
    "The team ___ (check) final measurements.": "El equipo revisa las medidas finales.",
    "The supervisor ___ (evaluate) worker performance.": "El supervisor evalúa el rendimiento del trabajador.",
    "The workers ___ (load) the truck now.": "Los trabajadores están cargando el camión ahora.",
    "The technician ___ (repair) equipment during inspection.": "El técnico repara el equipo durante la inspección.",
    "The quality team ___ (verify) product standards.": "El equipo de calidad verifica los estándares del producto.",
    "The manager ___ (conduct) a final meeting.": "El gerente dirige una reunión final.",
    "The products ___ finished yesterday.": "Los productos fueron terminados ayer.",
    "The warehouse ___ full today.": "El almacén está lleno hoy.",
    "The materials ___ available during production.": "Los materiales estaban disponibles durante la producción.",
    "The robot arm ___ functional during the test.": "El brazo robótico era funcional durante la prueba.",
    "The control panel ___ active yesterday.": "El panel de control estaba activo ayer.",
    "The workers ___ very efficient today.": "Los trabajadores son muy eficientes hoy.",
    "The engineer ___ responsible for the project.": "El ingeniero es/era responsable del proyecto.",
    "The supervisor ___ in the office now.": "El supervisor está en la oficina ahora.",
    "The technician ___ (calibrate) the machines.": "El técnico calibra las máquinas.",
    "The team ___ (organize) dispatch documents.": "El equipo organiza los documentos de despacho.",
    "___ the machine new?": "¿Es la máquina nueva?",
    "___ the workers in the factory now?": "¿Están los trabajadores en la fábrica ahora?",
    "___ the supervisor present yesterday?": "¿Estaba el supervisor presente ayer?",
    "___ the products ready for shipment?": "¿Están los productos listos para el envío?",
    "___ the report complete last week?": "¿Estaba el reporte completo la semana pasada?",
    "The workers ___ (assemble) final products.": "Los trabajadores ensamblan los productos finales.",
    "The engineer ___ (design) improvements now.": "El ingeniero está diseñando mejoras ahora.",
    "The technician ___ (test) equipment at the moment.": "El técnico está probando el equipo en este momento.",
    "The supervisor ___ (monitor) production today.": "El supervisor está monitoreando la producción hoy.",
    "The team ___ (prepare) delivery orders.": "El equipo prepara los pedidos de entrega.",
    "The machine ___ operational during the audit.": "La máquina estaba operativa durante la auditoría.",
    "The workers ___ in the assembly area now.": "Los trabajadores están en el área de ensamblaje ahora.",
    "The products ___ ready for export yesterday.": "Los productos estaban listos para la exportación ayer.",
    "The engineer ___ a good leader.": "El ingeniero es/era un buen líder.",
    "The warehouse ___ organized and clean.": "El almacén está/estaba organizado y limpio.",
    "The technician ___ present during inspection.": "El técnico estaba presente durante la inspección.",
    "The team ___ responsible for quality control.": "El equipo es responsable del control de calidad.",
    "The supervisor ___ checking final reports.": "El supervisor está revisando los reportes finales.",
    "The workers ___ loading the truck now.": "Los trabajadores están cargando el camión ahora.",
    "The machine ___ cutting wood yesterday.": "La máquina estaba cortando madera ayer.",
    "___ the engineer in the office today?": "¿Está el ingeniero en la oficina hoy?",
    "___ the workers ready now?": "¿Están los trabajadores listos ahora?",
    "___ the warehouse full yesterday?": "¿Estaba el almacén lleno ayer?",
    "___ the products finished today?": "¿Están los productos terminados hoy?",
    "___ the supervisor responsible for quality control?": "¿Es el supervisor responsable del control de calidad?"
}
